import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { Observable, map } from 'rxjs';

import { AppConsts } from '@shared/AppConsts';
import {
    CvDraft,
    ExportResult,
    Finding,
    ParseResult,
    PhotoOps,
    PhotoRenderResult,
    RewriteResult,
    SkillSuggestion,
    SummaryTone,
    TailorResult,
} from './cv.models';

/**
 * ELEVATOR — every server call the create flow makes.
 *
 * All of it is answered by MSW today (src/mocks/cv-handlers.ts); none of these
 * endpoints exists on the ABP backend yet — swagger.json has only Account,
 * Role, Session, Tenant and User. Kept in ONE service on purpose: the surface
 * is small, and a reader can see the whole contract the backend has to honour
 * without opening four files.
 *
 * NOT generated by NSwag. service-proxies.ts is regenerated from swagger.json
 * and would erase anything hand-written; when these endpoints land on the
 * backend, this file is deleted and the generated proxies take over.
 *
 * ABP wraps every response in `{ result, success, error, __abp }`, and the
 * mocks match that exactly. AbpHttpInterceptor only unwraps it for BLOB
 * responses — that is the path the NSwag proxies use — so a plain
 * HttpClient.post<T>() like the ones below receives the envelope intact and
 * has to unwrap it itself. `unwrap()` does that in one place.
 */

/** ABP's response envelope, as it actually arrives on a JSON request. */
interface AbpEnvelope<T> {
    result: T;
    success: boolean;
    error: { message: string; details?: string } | null;
}
@Injectable()
export class CvApiService {
    // Declared after the public surface: the lint config wants every
    // public member ahead of the private ones. Nothing here is read
    // during field initialisation, so the order is free.
    private readonly http = inject(HttpClient);

    /* ── Import ───────────────────────────────────────────────── */

    /**
     * Reads an uploaded CV. Returns a draft plus the dotted paths it was NOT
     * confident about, so the UI can flag rather than silently fill.
     */
    parse(file: File): Observable<ParseResult> {
        const body = new FormData();
        body.append('file', file, file.name);
        return unwrap(this.http.post<AbpEnvelope<ParseResult>>(this.url('CvParse/Parse'), body));
    }

    /* ── Writing help ─────────────────────────────────────────── */

    /**
     * Sharpens one bullet.
     *
     * `outcome` is required by contract, and is the whole point: the model is
     * never asked to guess a number. It rewrites around what the candidate
     * says actually changed, so every figure on the finished CV is one they
     * can defend in an interview.
     */
    rewriteBullet(original: string, outcome: string): Observable<RewriteResult> {
        return unwrap(
            this.http.post<AbpEnvelope<RewriteResult>>(this.url('CvAi/RewriteBullet'), { original, outcome })
        );
    }

    /** Assembles a summary from the draft. Nothing that is not already in it. */
    draftSummary(draft: CvDraft, tone: SummaryTone): Observable<RewriteResult> {
        return unwrap(this.http.post<AbpEnvelope<RewriteResult>>(this.url('CvAi/DraftSummary'), { draft, tone }));
    }

    /** Skills implied by the visitor's own experience and project prose. */
    suggestSkills(draft: CvDraft): Observable<SkillSuggestion[]> {
        return unwrap(this.http.post<AbpEnvelope<SkillSuggestion[]>>(this.url('CvAi/SuggestSkills'), { draft }));
    }

    /** Searchable phrasings of a job title. Normalises; never promotes. */
    normaliseTitle(title: string): Observable<string[]> {
        return unwrap(this.http.post<AbpEnvelope<string[]>>(this.url('CvAi/NormaliseTitle'), { title }));
    }

    /* ── Portrait ─────────────────────────────────────────────── */

    /**
     * Runs the named edits over the photo. Server-side, Qwen-Image-Edit,
     * ~$0.02 a render.
     *
     * The operations are named and separate on purpose: narrow edits produce
     * better results than one "enhance" black box, and a visitor trusts what
     * they can name. None of them touches the face — see the mock for the
     * constraint the real implementation has to keep.
     */
    enhancePhoto(dataUrl: string, ops: PhotoOps): Observable<PhotoRenderResult> {
        return unwrap(
            this.http.post<AbpEnvelope<PhotoRenderResult>>(this.url('CvPhoto/Enhance'), { image: dataUrl, ops })
        );
    }

    /* ── Review ───────────────────────────────────────────────── */

    /**
     * The finished CV, run back through the same parser that reads uploads.
     *
     * Costs nothing extra because the parser already exists for the import
     * path, and it is the only honest way to claim "ATS-ready": every
     * competitor asserts it, this shows it.
     */
    readBack(draft: CvDraft): Observable<Finding[]> {
        return unwrap(this.http.post<AbpEnvelope<Finding[]>>(this.url('CvReview/ReadBack'), { draft }));
    }

    /** Scores the draft against a pasted job ad. */
    tailor(draft: CvDraft, jobAd: string): Observable<TailorResult> {
        return unwrap(this.http.post<AbpEnvelope<TailorResult>>(this.url('CvReview/Tailor'), { draft, jobAd }));
    }

    /* ── Output ───────────────────────────────────────────────── */

    /**
     * `withPhoto` is a real parameter rather than a draft field: the same CV
     * is often sent to a market that expects a photo and one that rejects
     * them, so both variants have to be exportable without editing anything.
     */
    export(draft: CvDraft, format: 'pdf' | 'docx', withPhoto: boolean): Observable<ExportResult> {
        return unwrap(
            this.http.post<AbpEnvelope<ExportResult>>(this.url('CvExport/Create'), { draft, format, withPhoto })
        );
    }

    /* ── Persistence ──────────────────────────────────────────── */

    saveDraft(draft: CvDraft): Observable<{ id: string; savedAt: string }> {
        return unwrap(
            this.http.post<AbpEnvelope<{ id: string; savedAt: string }>>(this.url('CvDraft/Save'), { draft })
        );
    }

    loadDraft(): Observable<CvDraft | null> {
        return unwrap(this.http.get<AbpEnvelope<CvDraft | null>>(this.url('CvDraft/Get')));
    }

    /** Mirrors AppConsts.remoteServiceBaseUrl, which is '' while mocks are on. */
    private url(path: string): string {
        return `${AppConsts.remoteServiceBaseUrl}/api/services/app/${path}`;
    }
}

/**
 * Strips ABP's envelope and turns `success: false` into a real error, so a
 * failed call reaches the component's `error` branch instead of arriving as a
 * success with an undefined body.
 */
function unwrap<T>(source: Observable<AbpEnvelope<T>>): Observable<T> {
    return source.pipe(
        map((res) => {
            if (res && typeof res === 'object' && 'success' in res) {
                if (!res.success) {
                    throw new Error(res.error?.message ?? 'The request failed.');
                }
                return res.result;
            }
            // A backend that ever returns a bare payload still works.
            return res as unknown as T;
        })
    );
}
