/**
 * ELEVATOR — fonts worth probing for on the reader's machine.
 *
 * Detection is by measurement (see LocalFontsService), which can only answer
 * "is THIS font installed?" — it cannot enumerate. So the app carries a list of
 * the faces people actually have, grouped by where they come from. Anything
 * missing can still be typed in by hand in the picker.
 *
 * Kept deliberately broad: a CV is a document, and the whole point of this
 * feature is that someone can set theirs in the font their industry expects.
 */
export const CV_FONT_CANDIDATES: readonly string[] = [
    // Windows / Office
    'Arial',
    'Arial Black',
    'Arial Narrow',
    'Bahnschrift',
    'Book Antiqua',
    'Bookman Old Style',
    'Calibri',
    'Cambria',
    'Candara',
    'Century Gothic',
    'Comic Sans MS',
    'Consolas',
    'Constantia',
    'Corbel',
    'Courier New',
    'Ebrima',
    'Franklin Gothic Medium',
    'Gabriola',
    'Gadugi',
    'Garamond',
    'Georgia',
    'Impact',
    'Ink Free',
    'Javanese Text',
    'Leelawadee UI',
    'Lucida Console',
    'Lucida Sans Unicode',
    'Malgun Gothic',
    'Microsoft Sans Serif',
    'Mongolian Baiti',
    'MS Gothic',
    'MV Boli',
    'Myanmar Text',
    'Nirmala UI',
    'Palatino Linotype',
    'Segoe Print',
    'Segoe Script',
    'Segoe UI',
    'Segoe UI Historic',
    'SimSun',
    'Sitka',
    'Sylfaen',
    'Tahoma',
    'Times New Roman',
    'Trebuchet MS',
    'Verdana',
    'Yu Gothic',

    // macOS
    'American Typewriter',
    'Andale Mono',
    'Avenir',
    'Avenir Next',
    'Baskerville',
    'Big Caslon',
    'Bodoni 72',
    'Bradley Hand',
    'Brush Script MT',
    'Chalkboard',
    'Cochin',
    'Copperplate',
    'Didot',
    'Futura',
    'Geneva',
    'Gill Sans',
    'Helvetica',
    'Helvetica Neue',
    'Herculanum',
    'Hoefler Text',
    'Lucida Grande',
    'Marker Felt',
    'Menlo',
    'Monaco',
    'Optima',
    'Palatino',
    'Papyrus',
    'Phosphate',
    'Rockwell',
    'San Francisco',
    'SF Pro Display',
    'Skia',
    'Snell Roundhand',
    'Superclarendon',
    'Times',
    'Trattatello',
    'Zapfino',

    // Linux / open source
    'Cantarell',
    'DejaVu Sans',
    'DejaVu Sans Mono',
    'DejaVu Serif',
    'FreeMono',
    'FreeSans',
    'FreeSerif',
    'Liberation Mono',
    'Liberation Sans',
    'Liberation Serif',
    'Nimbus Roman',
    'Nimbus Sans',
    'Noto Sans',
    'Noto Serif',
    'Open Sans',
    'Oxygen',
    'PT Sans',
    'PT Serif',
    'Roboto',
    'Roboto Mono',
    'Roboto Slab',
    'Source Code Pro',
    'Source Sans Pro',
    'Source Serif Pro',
    'Ubuntu',
    'Ubuntu Mono',

    // Commonly installed extras
    'Cascadia Code',
    'Fira Code',
    'Fira Sans',
    'IBM Plex Sans',
    'IBM Plex Serif',
    'Inter',
    'JetBrains Mono',
    'Lato',
    'Merriweather',
    'Montserrat',
    'Nunito',
    'Poppins',
    'Raleway',
    'Rubik',
    'Work Sans',
] as const;
